name = "appraiz"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
main = "./src/entry.cloudflare.ts"

[[d1_databases]]
binding = "DB"
database_name = "appraiz"
database_id = "0aff19e8-0e73-48c8-885a-357fc123297f"

[vars]
# JWT_SECRET は wrangler secret put JWT_SECRET で設定
