/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuestIndexRouteImport } from './routes/guest/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminHackathonListIndexRouteImport } from './routes/admin/hackathonList/index'
import { Route as GuestAuthSignupRouteImport } from './routes/guest/auth/signup'
import { Route as GuestAuthLoginRouteImport } from './routes/guest/auth/login'
import { Route as AdminAuthLoginRouteImport } from './routes/admin/auth/login'
import { Route as AdminHackathonListIdSettingIndexRouteImport } from './routes/admin/hackathonList/$id/setting/index'
import { Route as AdminHackathonListIdResultIndexRouteImport } from './routes/admin/hackathonList/$id/result/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestIndexRoute = GuestIndexRouteImport.update({
  id: '/guest/',
  path: '/guest/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHackathonListIndexRoute = AdminHackathonListIndexRouteImport.update({
  id: '/admin/hackathonList/',
  path: '/admin/hackathonList/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestAuthSignupRoute = GuestAuthSignupRouteImport.update({
  id: '/guest/auth/signup',
  path: '/guest/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestAuthLoginRoute = GuestAuthLoginRouteImport.update({
  id: '/guest/auth/login',
  path: '/guest/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthLoginRoute = AdminAuthLoginRouteImport.update({
  id: '/admin/auth/login',
  path: '/admin/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHackathonListIdSettingIndexRoute =
  AdminHackathonListIdSettingIndexRouteImport.update({
    id: '/admin/hackathonList/$id/setting/',
    path: '/admin/hackathonList/$id/setting/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminHackathonListIdResultIndexRoute =
  AdminHackathonListIdResultIndexRouteImport.update({
    id: '/admin/hackathonList/$id/result/',
    path: '/admin/hackathonList/$id/result/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/': typeof AdminIndexRoute
  '/guest/': typeof GuestIndexRoute
  '/admin/auth/login': typeof AdminAuthLoginRoute
  '/guest/auth/login': typeof GuestAuthLoginRoute
  '/guest/auth/signup': typeof GuestAuthSignupRoute
  '/admin/hackathonList/': typeof AdminHackathonListIndexRoute
  '/admin/hackathonList/$id/result/': typeof AdminHackathonListIdResultIndexRoute
  '/admin/hackathonList/$id/setting/': typeof AdminHackathonListIdSettingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminIndexRoute
  '/guest': typeof GuestIndexRoute
  '/admin/auth/login': typeof AdminAuthLoginRoute
  '/guest/auth/login': typeof GuestAuthLoginRoute
  '/guest/auth/signup': typeof GuestAuthSignupRoute
  '/admin/hackathonList': typeof AdminHackathonListIndexRoute
  '/admin/hackathonList/$id/result': typeof AdminHackathonListIdResultIndexRoute
  '/admin/hackathonList/$id/setting': typeof AdminHackathonListIdSettingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/': typeof AdminIndexRoute
  '/guest/': typeof GuestIndexRoute
  '/admin/auth/login': typeof AdminAuthLoginRoute
  '/guest/auth/login': typeof GuestAuthLoginRoute
  '/guest/auth/signup': typeof GuestAuthSignupRoute
  '/admin/hackathonList/': typeof AdminHackathonListIndexRoute
  '/admin/hackathonList/$id/result/': typeof AdminHackathonListIdResultIndexRoute
  '/admin/hackathonList/$id/setting/': typeof AdminHackathonListIdSettingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/'
    | '/guest/'
    | '/admin/auth/login'
    | '/guest/auth/login'
    | '/guest/auth/signup'
    | '/admin/hackathonList/'
    | '/admin/hackathonList/$id/result/'
    | '/admin/hackathonList/$id/setting/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/guest'
    | '/admin/auth/login'
    | '/guest/auth/login'
    | '/guest/auth/signup'
    | '/admin/hackathonList'
    | '/admin/hackathonList/$id/result'
    | '/admin/hackathonList/$id/setting'
  id:
    | '__root__'
    | '/'
    | '/admin/'
    | '/guest/'
    | '/admin/auth/login'
    | '/guest/auth/login'
    | '/guest/auth/signup'
    | '/admin/hackathonList/'
    | '/admin/hackathonList/$id/result/'
    | '/admin/hackathonList/$id/setting/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  GuestIndexRoute: typeof GuestIndexRoute
  AdminAuthLoginRoute: typeof AdminAuthLoginRoute
  GuestAuthLoginRoute: typeof GuestAuthLoginRoute
  GuestAuthSignupRoute: typeof GuestAuthSignupRoute
  AdminHackathonListIndexRoute: typeof AdminHackathonListIndexRoute
  AdminHackathonListIdResultIndexRoute: typeof AdminHackathonListIdResultIndexRoute
  AdminHackathonListIdSettingIndexRoute: typeof AdminHackathonListIdSettingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest/': {
      id: '/guest/'
      path: '/guest'
      fullPath: '/guest/'
      preLoaderRoute: typeof GuestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/hackathonList/': {
      id: '/admin/hackathonList/'
      path: '/admin/hackathonList'
      fullPath: '/admin/hackathonList/'
      preLoaderRoute: typeof AdminHackathonListIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest/auth/signup': {
      id: '/guest/auth/signup'
      path: '/guest/auth/signup'
      fullPath: '/guest/auth/signup'
      preLoaderRoute: typeof GuestAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest/auth/login': {
      id: '/guest/auth/login'
      path: '/guest/auth/login'
      fullPath: '/guest/auth/login'
      preLoaderRoute: typeof GuestAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/auth/login': {
      id: '/admin/auth/login'
      path: '/admin/auth/login'
      fullPath: '/admin/auth/login'
      preLoaderRoute: typeof AdminAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/hackathonList/$id/setting/': {
      id: '/admin/hackathonList/$id/setting/'
      path: '/admin/hackathonList/$id/setting'
      fullPath: '/admin/hackathonList/$id/setting/'
      preLoaderRoute: typeof AdminHackathonListIdSettingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/hackathonList/$id/result/': {
      id: '/admin/hackathonList/$id/result/'
      path: '/admin/hackathonList/$id/result'
      fullPath: '/admin/hackathonList/$id/result/'
      preLoaderRoute: typeof AdminHackathonListIdResultIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  GuestIndexRoute: GuestIndexRoute,
  AdminAuthLoginRoute: AdminAuthLoginRoute,
  GuestAuthLoginRoute: GuestAuthLoginRoute,
  GuestAuthSignupRoute: GuestAuthSignupRoute,
  AdminHackathonListIndexRoute: AdminHackathonListIndexRoute,
  AdminHackathonListIdResultIndexRoute: AdminHackathonListIdResultIndexRoute,
  AdminHackathonListIdSettingIndexRoute: AdminHackathonListIdSettingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
